### ISSUE TITLE
Cloud Deployment & Documentation: Set Up EC2 Instance

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/nsc-events#35]
relates to #30

This issue is for setting up an AWS EC2 instance to run our web app on the cloud.

**Comment by Exochos** [comment]
![image](https://github.com/SeattleColleges/nsc-events/assets/35015441/8777365e-af05-4865-9196-4524c6f640d0)

![image](https://github.com/SeattleColleges/nsc-events/assets/35015441/a4a69963-0877-4dd8-8cbb-5c86c1b3d2e7)
![image](https://github.com/SeattleColleges/nsc-events/assets/35015441/612108d9-5566-45bf-a940-ff1316352fba)

![image](https://github.com/SeattleColleges/nsc-events/assets/35015441/49c4d780-db4a-40e7-b016-8a122f05ec1e)

**Comment by Exochos** [comment]
**Things of note:**

- I'm personally a big fan of Ubuntu in general, its what I run at home and have found it very user friendly, lots of good documentation out there for it and its free and open source.
- You will be required to create a key pair - I use putty at home so I created a .ppk file which is what Putty uses for SSH private keys. I am learning that other people tend to use command line SSH so for most people I would recommend the .pem filetype instead.
- We are allowed up to 30gig of hard drive space on the free tier, I went with 20gig which should be large enough for our instance and still allow us access to another instance if we need to spin up another instance for some reason.
- We only have one choice for the free tier instance type so that doesn't require much decisions. If you want lookup the p5 large and see how much that costs. The p5 large has 8 H100 GPU running in parallel in the background (each of which costs $40k for context), if we were training our own GPT model that is what we would be using.
- Make sure to allow access to HTTP and HTTPS as well as SSH, if you don't allow SSH you won't be able to access the instance (made that mistake once.) In some cases you shouldn't allow HTTP and just opt for HTTPS for security reasons. However we aren't to that point yet.
